
tfpduruccpbfyrjfwnso = "project_ref"

[functions.generate_profile]
verify_jwt = true

[functions.generate_companies]
verify_jwt = true

[functions.generate_contacts]
verify_jwt = true

[functions.generate_message]
verify_jwt = true
