
tfpduruccpbfyrjfwnso = "project_ref"

[functions.generate_profile]
verify_jwt = true

[functions.generate_companies]
verify_jwt = true

[functions.generate_contacts]
verify_jwt = true

[functions.generate_message]
verify_jwt = true

[functions.generate_guest_profile]
verify_jwt = false

[functions.link_guest_profile]
verify_jwt = false

[functions.get_companies_overview]
verify_jwt = true
